# Conda build file for package ae-preflight
# To build: conda build ae-preflight

package:
  name: ae_preflight
  version: '0.1.4'

source:
  path: .

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ae-preflight=ae_preflight.profile:main

requirements:
  build:
    - python >=2.7,<=3.7
    - setuptools
    - psutil

  run:
    - python
    - psutil

test:
  imports:
    - ae_preflight

  requires:
    - mock
    - nose
    - flake8

  commands:
    - flake8 . --exclude run_test.py

about:
  home: 'https://github.com/Anaconda-Platform/ae-preflight'
  license: 'Apache License, Version 2.0'
  license_file: LICENSE
  license_family: APACHE
  summary: 'Library to run preflight checks before installing Anaconda Enterprise'
  description: 'Library to run preflight checks before installing Anaconda Enterprise'
  dev_url: 'https://github.com/Anaconda-Platform/ae-preflight'
