# Conda build file for package ae-preflight
# To build: conda build ae-preflight

package:
  name: ae_preflight
  version: '0.1.9'

source:
  path: ../

build:
  number: 0
  script:
    - flake8
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir
  entry_points:
    - ae-preflight=ae_preflight.profile:main
  noarch: python

requirements:
  build:
    - python
    - pip
    - setuptools
    - flake8
  run:
    - python
    - psutil
    - distro

test:
  requires:
    - mock
    - nose
  source_files:
    - tests/
  commands:
    - nosetests tests

about:
  home: 'https://github.com/Anaconda-Platform/ae-preflight'
  license: 'Apache License, Version 2.0'
  license_file: LICENSE
  license_family: APACHE
  summary: 'Library to run preflight checks before installing Anaconda Enterprise'
  description: 'Library to run preflight checks before installing Anaconda Enterprise'
  dev_url: 'https://github.com/Anaconda-Platform/ae-preflight'
