name: Build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install the build environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install -y conda-build conda-verify constructor anaconda-client
        conda config --prepend channels ae5-admin
    - name: Build the package
      run: |
        source $CONDA/bin/activate
        conda build conda.recipe
    - name: Build the installer
      run: |
        source $CONDA/bin/activate
        pversion=$(ls $CONDA/conda-bld/noarch/ae_preflight-* | sed 's@^.*ae_preflight-@@;s@-.*@@')
        cversion=$(echo $pversion | sed 's@+@-@')
        sed -i.bak "s@version: .*@version: \"${cversion}\"@;s@- ae_preflight.*@- ae_preflight=${pversion}@" construct.yaml
        cat construct.yaml
        constructor
        cp ae_preflight-*-Linux-x86_64.sh ae_preflight-latest-Linux-x86_64.sh
        ls -l ae_preflight*.sh
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/bin/activate
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label main"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin $LABEL $CONDA/conda-bld/*/*.tar.bz2 --force
    - name: Upload installer
      if: github.event_name == 'push'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      run: |
        for fn in ae_preflight-*-Linux-x86_64.sh; do
          aws s3 cp $fn s3://airgap-svc/misc/ --acl public-read
        done
