name: Build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create the build environment
      run: |
        source $CONDA/bin/activate
        conda install -y conda conda-build conda-verify constructor
        conda config --prepend channels ae5-admin
    - name: Build the package
      run: |
        source $CONDA/bin/activate
        conda build conda.recipe
    - name: Build the installer
      run: |
        source $CONDA/bin/activate
        pversion=$(ls $CONDA/conda-bld/noarch/ae-preflight-* | sed 's@^.*ae-preflight-@@;s@-.*@@')
        cversion=$(echo $pversion | sed 's@+@-@')
        sed -i.bak "s@version: .*@version: \"${cversion}\"@;s@- ae-preflight.*@- ae-preflight=${pversion}@" construct.yaml
        cat construct.yaml
        constructor
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/bin/activate
        conda install -y anaconda-client
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label main"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin $LABEL $CONDA/conda-bld/*/*.tar.bz2 --force
    - name: Upload installer
      if: github.event_name == 'push'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      run: aws s3 cp ae_preflight-*-Linux-x86_64.sh s3://airgap.svc.anaconda.com/misc/ --acl public-read
